### ISSUE TITLE
compiler crash with attempt to redefine destructor

### ISSUE THREAD

**Issue by disruptek** [nim-works/nimskull#1161] opened 2024-02-02 21:28 UTC
### Specification

I managed to instantiate an object before defining a destructor for it, which caused the compiler to crash.

### Example
```nim
type Grenade = object
var g: Grenade
proc `=destroy`(g: var Grenade) = discard
```

### Actual Output
Compiler crash.

```
Traceback (most recent call last)
/home/adavidoff/git/nimskull/compiler/nim.nim(154) nim
/home/adavidoff/git/nimskull/compiler/nim.nim(89) handleCmdLine
/home/adavidoff/git/nimskull/compiler/front/main.nim(539) mainCommand
/home/adavidoff/git/nimskull/compiler/front/main.nim(491) compileToBackend
/home/adavidoff/git/nimskull/compiler/front/main.nim(214) commandCompileToC
/home/adavidoff/git/nimskull/compiler/modules/modules.nim(212) compileProject
/home/adavidoff/git/nimskull/compiler/modules/modules.nim(128) compileModule
/home/adavidoff/git/nimskull/compiler/sem/passes.nim(284) processModule
/home/adavidoff/git/nimskull/compiler/sem/passes.nim(102) processTopLevelStmt
/home/adavidoff/git/nimskull/compiler/sem/sem.nim(950) myProcess
/home/adavidoff/git/nimskull/compiler/sem/sem.nim(868) semStmtAndGenerateGenerics
/home/adavidoff/git/nimskull/compiler/sem/semstmts.nim(3364) semStmt
/home/adavidoff/git/nimskull/compiler/sem/semexprs.nim(1441) semExprNoType
/home/adavidoff/git/nimskull/compiler/sem/semexprs.nim(3854) semExpr
/home/adavidoff/git/nimskull/compiler/modules/importer.nim(405) evalImport
/home/adavidoff/git/nimskull/compiler/modules/importer.nim(362) impMod
/home/adavidoff/git/nimskull/compiler/modules/importer.nim(319) myImportModule
/home/adavidoff/git/nimskull/compiler/modules/modules.nim(161) importModule
/home/adavidoff/git/nimskull/compiler/modules/modules.nim(128) compileModule
/home/adavidoff/git/nimskull/compiler/sem/passes.nim(284) processModule
/home/adavidoff/git/nimskull/compiler/sem/passes.nim(102) processTopLevelStmt
/home/adavidoff/git/nimskull/compiler/sem/sem.nim(950) myProcess
/home/adavidoff/git/nimskull/compiler/sem/sem.nim(868) semStmtAndGenerateGenerics
/home/adavidoff/git/nimskull/compiler/sem/semstmts.nim(3364) semStmt
/home/adavidoff/git/nimskull/compiler/sem/semexprs.nim(1441) semExprNoType
/home/adavidoff/git/nimskull/compiler/sem/semexprs.nim(3843) semExpr
/home/adavidoff/git/nimskull/compiler/sem/semstmts.nim(2993) semRoutineDef
/home/adavidoff/git/nimskull/compiler/sem/semstmts.nim(2167) semProcAnnotation
/home/adavidoff/git/nimskull/compiler/sem/semstmts.nim(571) semAnnotation
/home/adavidoff/git/nimskull/compiler/sem/semstmts.nim(562) tryMacroPragma
/home/adavidoff/git/nimskull/compiler/sem/semexprs.nim(1190) afterCallActions
/home/adavidoff/git/nimskull/compiler/sem/sem.nim(788) semMacroExpr
/home/adavidoff/git/nimskull/compiler/sem/sem.nim(728) semAfterMacroCall
/home/adavidoff/git/nimskull/compiler/sem/semexprs.nim(3843) semExpr
/home/adavidoff/git/nimskull/compiler/sem/semstmts.nim(2993) semRoutineDef
/home/adavidoff/git/nimskull/compiler/sem/semstmts.nim(2167) semProcAnnotation
/home/adavidoff/git/nimskull/compiler/sem/semstmts.nim(571) semAnnotation
/home/adavidoff/git/nimskull/compiler/sem/semstmts.nim(562) tryMacroPragma
/home/adavidoff/git/nimskull/compiler/sem/semexprs.nim(1190) afterCallActions
/home/adavidoff/git/nimskull/compiler/sem/sem.nim(788) semMacroExpr
/home/adavidoff/git/nimskull/compiler/sem/sem.nim(728) semAfterMacroCall
/home/adavidoff/git/nimskull/compiler/sem/semexprs.nim(3664) semExpr
/home/adavidoff/git/nimskull/compiler/sem/semexprs.nim(1413) semDirectOp
/home/adavidoff/git/nimskull/compiler/sem/semexprs.nim(1150) semOverloadedCallAnalyseEffects
/home/adavidoff/git/nimskull/compiler/sem/semcall.nim(573) semOverloadedCall
/home/adavidoff/git/nimskull/compiler/sem/semcall.nim(326) resolveOverloads
/home/adavidoff/git/nimskull/compiler/sem/semcall.nim(73) pickBestCandidate
/home/adavidoff/git/nimskull/compiler/sem/sigmatch.nim(3155) matches
/home/adavidoff/git/nimskull/compiler/sem/sigmatch.nim(3055) matchesAux
/home/adavidoff/git/nimskull/compiler/sem/sigmatch.nim(2614) prepareOperand
/home/adavidoff/git/nimskull/compiler/sem/semexprs.nim(49) semOperand
/home/adavidoff/git/nimskull/compiler/sem/semexprs.nim(3664) semExpr
/home/adavidoff/git/nimskull/compiler/sem/semexprs.nim(1417) semDirectOp
/home/adavidoff/git/nimskull/compiler/sem/semexprs.nim(1190) afterCallActions
/home/adavidoff/git/nimskull/compiler/sem/sem.nim(788) semMacroExpr
/home/adavidoff/git/nimskull/compiler/sem/sem.nim(728) semAfterMacroCall
/home/adavidoff/git/nimskull/compiler/sem/semexprs.nim(3843) semExpr
/home/adavidoff/git/nimskull/compiler/sem/semstmts.nim(3025) semRoutineDef
/home/adavidoff/git/nimskull/compiler/sem/semstmts.nim(2776) semProc
/home/adavidoff/git/nimskull/compiler/sem/semstmts.nim(2712) semProcAux
/home/adavidoff/git/nimskull/compiler/sem/semexprs.nim(2348) semProcBody
/home/adavidoff/git/nimskull/compiler/sem/semexprs.nim(3821) semExpr
/home/adavidoff/git/nimskull/compiler/sem/semstmts.nim(3260) semStmtList
/home/adavidoff/git/nimskull/compiler/sem/semexprs.nim(3830) semExpr
/home/adavidoff/git/nimskull/compiler/sem/semstmts.nim(84) semWhile
/home/adavidoff/git/nimskull/compiler/sem/semstmts.nim(3364) semStmt
/home/adavidoff/git/nimskull/compiler/sem/semexprs.nim(1441) semExprNoType
/home/adavidoff/git/nimskull/compiler/sem/semexprs.nim(3821) semExpr
/home/adavidoff/git/nimskull/compiler/sem/semstmts.nim(3260) semStmtList
/home/adavidoff/git/nimskull/compiler/sem/semexprs.nim(3831) semExpr
/home/adavidoff/git/nimskull/compiler/sem/semstmts.nim(235) semTry
/home/adavidoff/git/nimskull/compiler/sem/semstmts.nim(103) semExprBranchScope
/home/adavidoff/git/nimskull/compiler/sem/semstmts.nim(95) semExprBranch
/home/adavidoff/git/nimskull/compiler/sem/semexprs.nim(3821) semExpr
/home/adavidoff/git/nimskull/compiler/sem/semstmts.nim(3260) semStmtList
/home/adavidoff/git/nimskull/compiler/sem/semexprs.nim(3689) semExpr
/home/adavidoff/git/nimskull/compiler/sem/semexprs.nim(2916) semMagic
/home/adavidoff/git/nimskull/compiler/sem/semexprs.nim(1413) semDirectOp
/home/adavidoff/git/nimskull/compiler/sem/semexprs.nim(1150) semOverloadedCallAnalyseEffects
/home/adavidoff/git/nimskull/compiler/sem/semcall.nim(573) semOverloadedCall
/home/adavidoff/git/nimskull/compiler/sem/semcall.nim(326) resolveOverloads
/home/adavidoff/git/nimskull/compiler/sem/semcall.nim(73) pickBestCandidate
/home/adavidoff/git/nimskull/compiler/sem/sigmatch.nim(3155) matches
/home/adavidoff/git/nimskull/compiler/sem/sigmatch.nim(3055) matchesAux
/home/adavidoff/git/nimskull/compiler/sem/sigmatch.nim(2614) prepareOperand
/home/adavidoff/git/nimskull/compiler/sem/semexprs.nim(49) semOperand
/home/adavidoff/git/nimskull/compiler/sem/semexprs.nim(3689) semExpr
/home/adavidoff/git/nimskull/compiler/sem/semexprs.nim(2916) semMagic
/home/adavidoff/git/nimskull/compiler/sem/semexprs.nim(1413) semDirectOp
/home/adavidoff/git/nimskull/compiler/sem/semexprs.nim(1150) semOverloadedCallAnalyseEffects
/home/adavidoff/git/nimskull/compiler/sem/semcall.nim(573) semOverloadedCall
/home/adavidoff/git/nimskull/compiler/sem/semcall.nim(326) resolveOverloads
/home/adavidoff/git/nimskull/compiler/sem/semcall.nim(56) pickBestCandidate
/home/adavidoff/git/nimskull/compiler/sem/sigmatch.nim(158) initCallCandidate
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

### Expected Output
```
Error: cannot bind another '=destroy' to: Grenade
```
### Possible Solution

Don't dereference nil.

### Additional Information
My workaround looks like this:
```nim
proc initCallCandidate*(ctx: PContext, c: var TCandidate, callee: PSym,
                        calleeScope = -1) =
  initCandidate(ctx, c, callee.typ)
  c.calleeSym = callee
  if callee.kind in skProcKinds and calleeScope == -1:
    if callee.originatingModule == ctx.module:
      c.calleeScope = 2
      var owner = callee
      while true:  # line 156 in compiler/sem/sigmatch.nim      
        # owner becomes nil...
        owner = owner.skipGenericOwner                                            
        if owner.isNil:                                                           
          # i reset it here to work around the bug                                      
          owner = callee                                                                
          break                                                                         
        else:                                                                           
          if owner.kind == skModule: break                                              
          inc c.calleeScope
```

**Comment by zerbina** [comment] 2024-02-02 21:41
I've tried it out locally, but am unable reproduce the crash with the provided snippet. Instead, I get the expected error message.

Going over the stack-trace, it looks like the error occurs within the expansion of a macro/template pragma.

**Comment by disruptek** [comment] 2024-02-03 13:11
The problem occurred in a larger project but not within a macro/template; rather, it was top-level statements within an imported module.

**Comment by saem** [comment] 2024-02-03 17:45
The stack trace suggests that:
- there is an active import of a module being processed
- a routine is being analysed that has a macro pragma
- it's three macros deep transforming a routine
- and within the body there is a try within a while

Something like that, but it sounds like a CPS rewrite.

I'm guessing something is wrong with fixing up symbols from macros output in the compiler that's leading to this issue.

**Comment by saem** [comment] 2024-02-04 20:38
Presently, if you can put your code up somewhere @disruptek, I can run compiler tracing on it and see if it sheds some additional light so we can get to a minimal reproduction and fix.

**Comment by zerbina** [comment] 2024-02-12 18:07
I believe the owner is `nil` for the same reason as it is with compiler-generated enum-to-string procedures (`$`; refer to #1182). A minimal reproduction of what I think is the same bug as described by this issue:

```nim
# pass-through macro, but it is important that the parameter is `typed` 
macro m(x: typed): untyped = x

type Grenade = object

m:
  proc f() =
    var g: Grenade
    `=destroy`(g) # this is the call that causes the NPE in `initCallCandidate`

```

**Comment by saem** [comment] 2024-02-23 03:44
This should be fixed as part of https://github.com/nim-works/nimskull/pull/1205.

**Closed as completed by saem** 2024-02-23 03:44 UTC
Labels: bug, compiler/sem
