### ISSUE TITLE
dereferencing `var|lent uint(8|16|32)` yields wrong value in VM

### ISSUE THREAD

**Issue by alaviss** [nim-works/nimskull#1407] opened 2024-08-08 08:04 UTC
### Example

```nim
proc foo(values: openArray[uint16]) =
  for value in values.items:
    doAssert value == 40000u16:
      "Got: " & $value

foo([40000u16])
```

### Actual Output

```
$ nim r --backend:vm test.nim
stack trace: (most recent call last)
test.nim(1, 2) NimMain
test.nim(6, 4) test
test.nim(3, 14) foo
assertions.nim(38, 26) failedAssertImpl
assertions.nim(28, 11) raiseAssert
fatal.nim(50, 5) sysFatal
fatal.nim(50, 5) Error: unhandled exception: test.nim(3, 14) `value == 40000'u16` Got: 18446744073709526080 [AssertionDefect]

```

### Additional Information

* Values between 0 - 32767 (`high(int16)`) does not exhibit this issue.
* This only happens if the array was accessed via `items`.

**Comment by zerbina** [comment] 2024-08-08 15:47
Thanks for filing the issue!

The problem is not directly related to `openArray` and `uint16`, but instead affects all `lent uint(8|16|32)` and `var uint(8|16|32)` dereferences, with the reason being that `vmgen` doesn't emit the necessary narrowing instructions.

A more minimized reproducer:
```nim
proc f(x: (uint8,)): lent uint8 = x[0]

echo f((128'u8,)) # echoes 0xFFFFFFFF_FFFFFF80 (as a non-hex number)
```

**Comment by saem** [comment] 2024-08-08 20:25
Fixed in https://github.com/nim-works/nimskull/pull/1409

**Closed as completed by saem** 2024-08-08 20:25 UTC
Labels: bug, compiler/vm
